version: '3.7'

services:
  nginx:
    image: gitea.kidsec.pl/vrozaksen/nginx:latest
    container_name: ahe-projekt-nginx
    mem_reservation: 128M
    volumes:
      - .:/application
    depends_on:
      - php
    networks:
      - ahe-net
      - npm-net
  php:
    image: gitea.kidsec.pl/vrozaksen/php:latest
    container_name: ahe-projekt-php
    mem_reservation: 512M
    volumes:
      - .:/application
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /application
    depends_on:
      - db
    networks:
      - ahe-net
      - npm-net
  db:
    image: mariadb
    container_name: ahe-projekt-db
    command: --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=45MVVyX7P95FsTKs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sSfNo8C4pTHTzxV5
      - MYSQL_DATABASE=laravel
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    networks:
      - ahe-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ahe-projekt-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - ahe-net
      - npm-net
networks:
  ahe-net:
    internal: true
  npm-net:
    external: true
