version: '3.7'

services:
  nginx:
    build: ./docker/nginx
    pull_policy: build
    container_name: ahe-projekt-nginx
    mem_reservation: 128M
    volumes:
      - .:/application
    depends_on:
      - php
    networks:
      - ahe-net
      - npm_default

  php:
    image: php:8.2.0-fpm
    container_name: ahe-projekt-php
    build: ./docker/php
    pull_policy: build
    mem_reservation: 512M
    volumes:
      - .:/application
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /application
    depends_on:
      - mysql
    networks:
      - ahe-net

  mysql:
    image: mariadb:10.3.27
    container_name: ahe-projekt-mysql
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelWebsite
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    networks:
      - ahe-net

networks:
  ahe-net:
    name: ahe-net
    internal: true
  npm_default:
    name: npm_default
    external: true