version: '3.7'

services:
  nginx:
    build: ./docker/nginx
    pull_policy: build
    container_name: ahe-projekt-nginx
    mem_reservation: 128M
    volumes:
      - .:/application
    depends_on:
      - php
    networks:
      - ahe-net
      - npm_default

  php:
    image: php:8.2.0-fpm
    container_name: ahe-projekt-php
    build: ./docker/php
    pull_policy: build
    mem_reservation: 512M
    volumes:
      - .:/application
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /application
    depends_on:
      - db
    networks:
      - ahe-net
# DB Done. Remmeber ro edit .env or database.php
  db:
    image: mariadb
    container_name: ahe-projekt-db
    command: --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=45MVVyX7P95FsTKs
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=sSfNo8C4pTHTzxV5
      - MYSQL_DATABASE=laravel
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    networks:
      - ahe-net
# Should be good
networks:
  ahe-net:
    name: ahe-net
    internal: true
  npm_default:
    name: npm_default
    external: true