version: '3.7'

services:
  nginx:
    image: gitea.kidsec.pl/vrozaksen/nginx:latest
#    build: ./docker/nginx
#    pull_policy: build
    container_name: ahe-projekt-nginx
    mem_reservation: 128M
    volumes:
      - .:/application
    depends_on:
      - php
    networks:
      - ahe-net
      - npm_default

  php:
    image: gitea.kidsec.pl/vrozaksen/php:latest
    container_name: ahe-projekt-php
#    build: ./docker/php
#    pull_policy: build
    mem_reservation: 512M
    volumes:
      - .:/application
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /application
    depends_on:
      - db
      - npm
    networks:
      - ahe-net
      - npm_default
# DB Done. Remmeber ro edit .env or database.php
  db:
    image: mariadb
    container_name: ahe-projekt-db
    command: --explicit_defaults_for_timestamp
    environment:
      - MYSQL_ROOT_PASSWORD=45MVVyX7P95FsTKs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sSfNo8C4pTHTzxV5
      - MYSQL_DATABASE=laravel
    restart: always
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    networks:
      - ahe-net

  npm:
    image: ahe-projekt-npm
    build: ./docker/npm
    container_name: ahe-projekt-npm
    command: run dev
    volumes:
      - .:/application
      - .env:/application/.env
    ports:
      - 3444:3000
      - 3445:3001
    working_dir: /application
    entrypoint: ['npm']
    networks:
      - ahe-net
      - npm_default

# Should be good
networks:
  ahe-net:
    name: ahe-net
    internal: true
  npm_default:
    name: npm_default
    external: true
